export default [
  {
    id: 1,
    firstName: "Emmy",
    lastName: "Expo",
    title: "Business Analyst",
    experience: 13,
    workedWith: [2, 3],
    colleagues: "",
    avatar: "https://i.ibb.co/F8bgWpN/3-Beautiful-girl-with-a-gentle-smile.jpg",
  },
  {
    id: 2,
    firstName: "Roman",
    lastName: "React",
    title: "Marketing Specialist",
    experience: 7,
    workedWith: [1, 3],
    colleagues: "",
    avatar:
      "https://i.ibb.co/YWfqZN3/anastasia-vityukova-rp-F3p-Rr-E9g-unsplash.jpg",
  },
  {
    id: 3,
    firstName: "Amir",
    lastName: "Angular",
    title: "Project Manager",
    experience: 3,
    workedWith: [1, 2],
    avatar:
      "https://i.ibb.co/8DDkgz9/art-hauntington-jz-Y0-KRJop-EI-unsplash.jpg",
  },
  {
    id: 4,
    firstName: "Matt",
    lastName: "Mongoose",
    title: "UX Designer",
    experience: 1,
    workedWith: [6],
    avatar: "",
  },
  {
    id: 5,
    firstName: "Zoey",
    lastName: "Zoom",
    title: "Sales Director",
    experience: 9,
    workedWith: [],
    avatar: "",
  },
  {
    id: 6,
    firstName: "Judy",
    lastName: "Jest",
    title: "Marketing Specialist",
    experience: 5,
    workedWith: [4],
    avatar:
      "https://i.ibb.co/c6FQQF5/houcine-ncib-B4-Tj-Xn-I0-Y2c-unsplash.jpg",
  },
];
